# Generated by Django 4.1 on 2025-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='conteudo',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
