# Generated by Django 4.1 on 2025-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_conteudo_noticia_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='descricao',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=90),
        ),
    ]
