# Generated by Django 4.1.13 on 2025-11-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoCoordenativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('conector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenacoes.conector')),
                ('oracao_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeira', to='coordenacoes.oracao')),
                ('oracao_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segunda', to='coordenacoes.oracao')),
            ],
        ),
        migrations.AddField(
            model_name='conector',
            name='tipo_relacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenacoes.tiporelacao'),
        ),
    ]
